version: '3.0'

services:
  nginx:
    image: nginx:1.17
    container_name: experiment-docker-nginx-proxy-proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  site1:
    image: httpd:2.4
    container_name: experiment-docker-nginx-proxy-site1
    ports:
      - 8081:80
    volumes:
      - ./site1:/usr/local/apache2/htdocs/

  site2:
    image: httpd:2.4
    container_name: experiment-docker-nginx-proxy-site2
    ports:
      - 8082:80
    volumes:
      - ./site2:/usr/local/apache2/htdocs/
